version: '3.8'

services:
  app:
    build: .
    restart: always
    ports:
      - "443:443"
    environment:
      - HOST=4272517-lw36995.twc1.net
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=your_secure_password  # Измените на безопасный пароль
      - DB_NAME=devices_db
      - SSL_CERT=/app/certs/cert.pem
      - SSL_KEY=/app/certs/key.pem
    volumes:
      - ./fcm-config.json:/app/fcm-config.json
      - ./certs:/app/certs  # Монтируем директорию с сертификатами
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=your_secure_password  # Тот же пароль
      - POSTGRES_DB=devices_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: 