CREATE TABLE IF NOT EXISTS devices (
    id SERIAL PRIMARY KEY,
    token VARCHAR(255) NOT NULL,
    model VARCHAR(100),
    first_seen_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
); 